// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Airlines.Apis.Models
{
    public partial class AirPort
    {
        public AirPort()
        {
            FlightFromIdAirPortNavigations = new HashSet<Flight>();
            FlightToIdAirPortNavigations = new HashSet<Flight>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Flight> FlightFromIdAirPortNavigations { get; set; }
        public virtual ICollection<Flight> FlightToIdAirPortNavigations { get; set; }
    }
}